export type ENVVariable =
  | "AWS_REGION"
  | "MONITOR_TABLE_NAME"
  | "MONITOR_TABLE_GSI_NAME"
  | "STATE_MACHINE_ARN"
  | "TELEGRAM_BOT_TOKEN_SECRET_ID"
  | "TELEGRAM_BOT_PATH"
  | "USER_TABLE_NAME";
